### ISSUE TITLE
Неверный результат при операции добавления на баланс

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#10]
# Описание
При операции добавления на баланс итоговая сумма рассчитывается неверно

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L66

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 500.
2. Выполнить операцию пополнения баланса на 3000.

*Ожидаемый результат:* Остаток на балансе 3500.
*Фактический результат:* Остаток на балансе 3000.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L42-L50

# Скриншот
<img width="876" alt="Снимок экрана 2023-05-14 в 20 10 33" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/b6c4fc74-d3c5-4988-b6c9-6de39006043d">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
