### ISSUE TITLE
При операции оплаты баланс может стать отрицательным

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#11]
# Описание
При операции оплаты если баланс меньше суммы оплаты, то баланс становится отрицательным

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 500.
2. Выполнить операцию оплаты на 600.

*Ожидаемый результат:* Остаток на балансе 500.
*Фактический результат:* Остаток на балансе -600.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/4a0af9d2d9619ca5649f1ce11dc2c17632668a82/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L42-L49

# Скриншот
<img width="876" alt="Снимок экрана 2023-05-14 в 20 17 00" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/3615a4c3-2eba-414f-b816-8c287d06d771">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
