### ISSUE TITLE
Неверный результат при операции расчёта процентов

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#12]
# Описание
При операции расчёта процентов с положительным балансом, проценты рассчитываются неверно.

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/4a0af9d2d9619ca5649f1ce11dc2c17632668a82/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 200 и ставкой 15.
2. Выполнить операцию по расчёту процентов.

*Ожидаемый результат:* 0 процентов.
*Фактический результат:* 30 процентов.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/4a0af9d2d9619ca5649f1ce11dc2c17632668a82/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L61-L68

# Скриншот
<img width="876" alt="Снимок экрана 2023-05-14 в 20 22 38" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/4d6abafa-df86-413b-b7c8-33bbd601fa0a">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
