### ISSUE TITLE
IllegalArgumentException не выкидывается при негативном кредитном лимите

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#13]
# Описание
При негативном кредитном лимите не выкидывается IllegalArgumentException.

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/3844dd4b789d7f9def952c9a2f023ee1d36f837d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Создать объект класса CreditAccount с кредитным лимитом  -5500.

*Ожидаемый результат:* Выкидывается исключение IllegalArgumentException.
*Фактический результат:* Исключение не выкидывается.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/3844dd4b789d7f9def952c9a2f023ee1d36f837d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L22-L29

# Скриншот
<img width="1024" alt="Снимок экрана 2023-05-14 в 23 25 47" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/c6ca0374-178a-438c-89c7-1108ea7e083e">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
