### ISSUE TITLE
IllegalArgumentException не выкидывается при негативном начальном балансе

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#14]
# Описание
При негативном начальном балансе не выкидывается IllegalArgumentException.

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/3844dd4b789d7f9def952c9a2f023ee1d36f837d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом  -500.

*Ожидаемый результат:* Выкидывается исключение IllegalArgumentException.
*Фактический результат:* Исключение не выкидывается.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/3844dd4b789d7f9def952c9a2f023ee1d36f837d/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L31-L39

# Скриншот
<img width="1024" alt="Снимок экрана 2023-05-14 в 23 27 20" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/e16cf416-c047-4865-a2b4-13e2b5a1a594">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
