### ISSUE TITLE
IllegalArgumentException не выкидывается при балансе больше кредитного лимита

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#24]
# Описание
При балансе больше кредитного лимита не выкидывается IllegalArgumentException.

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/3844dd4b789d7f9def952c9a2f023ee1d36f837d/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 20000 и кредитным лимитом  55000.

*Ожидаемый результат:* Выкидывается исключение IllegalArgumentException.
*Фактический результат:* Исключение не выкидывается.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/cb2c1ca685b4dcb2dbd4b7edf4a537287bcbcaf7/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L78-L86

# Скриншот
<img width="1001" alt="Снимок экрана 2023-05-26 в 01 06 29" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/5bbd1dee-6b5a-4837-a098-c46ba5ff44a5">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Fixed by commit 60be55d
