### ISSUE TITLE
Неверный результат операции оплаты при оплате на отрицательную сумму

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#25]
# Описание
При операции оплаты если баланс меньше суммы оплаты, то баланс становится отрицательным

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 5000.
2. Выполнить операцию оплаты на -300.

*Ожидаемый результат:* Остаток на балансе 5000.
*Фактический результат:* Остаток на балансе 5300.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/ed04c3da9b9cb6020bff34f0ed13ed781dfa3f6c/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L88-L95

# Скриншот
<img width="1001" alt="Снимок экрана 2023-05-26 в 01 12 05" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/fc10c281-09ab-4573-8702-cfaa9d1efd7d">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Fixed by commit 60be55d
