### ISSUE TITLE
Неверный результат при операции расчета процентов

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#26]
# Описание
При операции расчёта процентов с положительным балансом, проценты рассчитываются неверно.

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/4a0af9d2d9619ca5649f1ce11dc2c17632668a82/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L83

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом -51 и ставкой 15.
2. Выполнить операцию по расчёту процентов.

*Ожидаемый результат:* -7 процентов.
*Фактический результат:* 0 процентов.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/72f3ba2a217dd2787cffaec433a8238e4c47f41b/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L97-L103

# Скриншот

<img width="1001" alt="Снимок экрана 2023-05-26 в 01 16 09" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/6fd15fb3-e5dc-4618-a879-824c8f352fef">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Fixed by commit 60be55d
