### ISSUE TITLE
Неверный результат при операции по оплате

### ISSUE THREAD

**Issue by bctrv** [bctrv/javaqa-team-diplom-2#9]
# Описание
При операции оплаты результат остатка на балансе рассчитывается неверно

# Локация дефекта
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L41

# Шаги воспроизведения
1. Создать объект класса CreditAccount с начальным балансом 500.
2. Выполнить операцию оплаты на 300.

*Ожидаемый результат:* Остаток на балансе 200.
*Фактический результат:* Остаток на балансе -300.

# Тест
https://github.com/bctrv/javaqa-team-diplom-2/blob/0c7d3ffe4cc182d9469863b311425cf9142a89d8/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L33-L40

# Скриншот
<img width="876" alt="Снимок экрана 2023-05-14 в 20 03 57" src="https://github.com/bctrv/javaqa-team-diplom-2/assets/125037420/9c131b1b-b45e-47c0-a288-1c583b048952">

# Окружение
* **Операционная система:** macOs Ventura 13.3.1
* **IDE:** IntelliJ IDEA 2022.3.3 (Community Edition)
* **Java:** Open JDK 11

**Comment by Katya6568** [comment]
Исправлено коммитом [4722321](https://github.com/bctrv/javaqa-team-diplom-2/commit/4722321575636cca9b303df78a7aef820b3aabd2)
